name: azure-nightly-build

on:
  schedule:
  # Runs "at midnight every day" (see https://crontab.guru)
  # will base on default branch `main`
  - cron: '0 3 * * *'
  push:
    branches:
    - mkulke/e2etest

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

permissions: {}

jobs:
  generate-podvm-image-version:
    if: github.event.inputs.podvm-image-id == ''
    runs-on: ubuntu-24.04
    outputs:
      image-version: "${{ steps.generate-image-version.outputs.image-version }}"
    steps:
    - name: Generate PodVM image version
      id: generate-image-version
      run: |
        nightly_version=$(date +'%Y.%m.%d')
        echo "Generated nightly version for the image as: ${nightly_version}"
        echo "image-version=${nightly_version}" >> "$GITHUB_OUTPUT"

  build-podvm-image:
    runs-on: ubuntu-24.04
    steps:
    - name: dummy step
      run: echo "This is a dummy step"
    needs:
    - generate-podvm-image-version
    outputs:
      image-id: "/CommunityGalleries/cocopodvm-d0e4f35f-5530-4b9c-8596-112487cdea85/Images/podvm_image0/Versions/2025.10.14"
    # uses: ./.github/workflows/azure-podvm-image-build.yml
    # permissions:
    #   id-token: write
    #   contents: read
    #   packages: write
    #   attestations: write
    # with:
    #   image-version: ${{ needs.generate-podvm-image-version.outputs.image-version }}
    #   git-ref: mkulke/e2etest
    # secrets:
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  run-e2e-test:
    uses: ./.github/workflows/azure-e2e-test.yml
    needs:
    - build-podvm-image
    permissions:
      id-token: write
    with:
      podvm-image-id: ${{ needs.build-podvm-image.outputs.image-id }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
