# (C) Copyright Confidential Containers Contributors 2023.
# SPDX-License-Identifier: Apache-2.0
#
# Daily run the e2e tests for libvirt.
---
name: daily e2e tests for libvirt

on:
  schedule:
  # Runs "at 04:15(UTC time) every day" (see https://crontab.guru)
  # will base on default branch `main`
    - cron: '15 4 * * *'
  workflow_dispatch:
    inputs:
      git-ref:
        type: string
        default: 'refs/heads/main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    uses: ./.github/workflows/e2e_run_all.yaml
    with:
      caa_image_tag: latest
      git_ref: ${{ inputs.git-ref || 'refs/heads/main' }}
      podvm_image_tag: latest
      registry: ghcr.io/${{ github.repository_owner }}/libvirt
    secrets: inherit
