name: libvirt-podvm-image-build

on:
  push:
    branches:
      - mkulke/libvirt-efi

jobs:
  build-podvm-image:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src/cloud-api-adaptor/podvm-mkosi

    steps:
    - name: Clone cloud-api-adaptor repository
      uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build binaries
      run: |
        make fedora-binaries-builder
        make binaries

    - name: Build image
      run: make image

    - uses: actions/upload-artifact@v4
      with:
        name: system.raw
        path: src/cloud-api-adaptor/podvm-mkosi/build/system.raw
